-- 11/5/2011 --
ALTER TABLE ef_users ADD COLUMN email2 VARCHAR(500);
ALTER TABLE ef_users ADD COLUMN email3 VARCHAR(500);
ALTER TABLE ef_users ADD COLUMN email4 VARCHAR(500);
ALTER TABLE ef_users ADD COLUMN email5 VARCHAR(500);

ALTER TABLE ef_users MODIFY COLUMN user_cookie VARCHAR(500);